/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ObjetivosRouteImport } from './routes/objetivos'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as MatrizRouteImport } from './routes/matriz'
import { Route as DependenciasRouteImport } from './routes/dependencias'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivosRoute = ObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrizRoute = MatrizRouteImport.update({
  id: '/matriz',
  path: '/matriz',
  getParentRoute: () => rootRouteImport,
} as any)
const DependenciasRoute = DependenciasRouteImport.update({
  id: '/dependencias',
  path: '/dependencias',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/dependencias': typeof DependenciasRoute
  '/matriz': typeof MatrizRoute
  '/metricas': typeof MetricasRoute
  '/objetivos': typeof ObjetivosRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/dependencias': typeof DependenciasRoute
  '/matriz': typeof MatrizRoute
  '/metricas': typeof MetricasRoute
  '/objetivos': typeof ObjetivosRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/dependencias': typeof DependenciasRoute
  '/matriz': typeof MatrizRoute
  '/metricas': typeof MetricasRoute
  '/objetivos': typeof ObjetivosRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/dependencias'
    | '/matriz'
    | '/metricas'
    | '/objetivos'
    | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/dependencias'
    | '/matriz'
    | '/metricas'
    | '/objetivos'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/dependencias'
    | '/matriz'
    | '/metricas'
    | '/objetivos'
    | '/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  DependenciasRoute: typeof DependenciasRoute
  MatrizRoute: typeof MatrizRoute
  MetricasRoute: typeof MetricasRoute
  ObjetivosRoute: typeof ObjetivosRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivos': {
      id: '/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof ObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matriz': {
      id: '/matriz'
      path: '/matriz'
      fullPath: '/matriz'
      preLoaderRoute: typeof MatrizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependencias': {
      id: '/dependencias'
      path: '/dependencias'
      fullPath: '/dependencias'
      preLoaderRoute: typeof DependenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  DependenciasRoute: DependenciasRoute,
  MatrizRoute: MatrizRoute,
  MetricasRoute: MetricasRoute,
  ObjetivosRoute: ObjetivosRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
